### PR TITLE
chore(release): 1.0.0

### LINKED ISSUE #71: Release v1
https://github.com/dequelabs/walnut/pull/1191#discussion_r530737485

### PR DESCRIPTION
**Pull request by stephenmathieson**
Closes #71

### CODE REVIEW

**Comment by erik-deque** [comment]
PRs in this release need to be reviewed for security (and marked as such).

**Comment by stephenmathieson** [comment]
I've reviewed each of the commits (other than my own) for security.

**Review by erik-deque — APPROVED** [review]
lgtm

**Comment by erik-deque** [comment]
# Release Audit
- [x] #1 
- [x] #72 
- [x] #76 
- [x] #79 
- [x] #69

**Comment by dylanb** [comment]
reviewed

**Pull request merged**
